// Type declarations for @liquicode/jsonstor-redis
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored on a Redis or Valkey server.

declare module '@liquicode/jsonstor-redis'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** The name or address of the Redis or Valkey server. */
		Server: string;
		/** The service port of the server. Defaults to `6379`. */
		Port?: number;
		/** Which of the server's numbered databases to use. A server offers sixteen by default and `0` is the one a client gets without asking. Defaults to `0`. */
		Database?: number;
		/** The user to connect as. Empty means none, and is what a server with no ACL expects. Defaults to `''`. */
		UserName?: string;
		/** That user's password. Empty means none. Defaults to `''`. */
		Password?: string;
		/** Encrypt the connection with TLS. Off by default so that a local server connects; a hosted Redis or Valkey requires it on. Defaults to `false`. */
		Encrypt?: boolean;
		/** Accept a certificate the machine does not trust, which is what a local server presents. Turn this off wherever `Encrypt` is on and the certificate is a real one. Defaults to `true`. */
		TrustServerCertificate?: boolean;
		/** The collection this storage reads and writes. It is the name of the single hash which holds the collection's documents. */
		CollectionName: string;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** `'jsonstor-redis'`. The package's bare name, which `Aliases` maps onto a prime. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
		/** This package's prime versions, each registering under its own name. */
		Adapters: StorageAdapter[];
		/** Every other name this package answers to, mapped to the prime it resolves to. */
		Aliases: { [ AliasName: string ]: string };
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-redis.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];
	export const Adapters: StorageAdapter[ 'Adapters' ];
	export const Aliases: StorageAdapter[ 'Aliases' ];

}
